export const CREATE_COMMUNITY_POST_REQUEST = "CREATE_COMMUNITY_POST_REQUEST";
export const CREATE_COMMUNITY_POST_SUCCESS = "CREATE_COMMUNITY_POST_SUCCESS";
export const CREATE_COMMUNITY_POST_FAIL = "CREATE_COMMUNITY_POST_FAIL";

export const EDIT_COMMUNITY_POST_REQUEST = "EDIT_COMMUNITY_POST_REQUEST";
export const EDIT_COMMUNITY_POST_SUCCESS = "EDIT_COMMUNITY_POST_SUCCESS";
export const EDIT_COMMUNITY_POST_FAIL = "EDIT_COMMUNITY_POST_FAIL";

export const GET_A_COMMUNITY_POST_REQUEST = "GET_A_COMMUNITY_POST_REQUEST";
export const GET_A_COMMUNITY_POST_SUCCESS = "GET_A_COMMUNITY_POST_SUCCESS";
export const GET_A_COMMUNITY_POST_FAIL = "GET_A_COMMUNITY_POST_FAIL";

export const GET_COMMUNITY_POSTS_REQUEST = "GET_COMMUNITY_POSTS_REQUEST";
export const GET_COMMUNITY_POSTS_SUCCESS = "GET_COMMUNITY_POSTS_SUCCESS";
export const GET_COMMUNITY_POSTS_FAIL = "GET_COMMUNITY_POSTS_FAIL";

export const DELETE_COMMUNITY_POST_REQUEST = "DELETE_COMMUNITY_POST_REQUEST";
export const DELETE_COMMUNITY_POST_SUCCESS = "DELETE_COMMUNITY_POST_SUCCESS";
export const DELETE_COMMUNITY_POST_FAIL = "DELETE_COMMUNITY_POST_FAIL";

export const COMMUNITY_IMAGE_UPLOAD_REQUEST = "COMMUNITY_IMAGE_UPLOAD_REQUEST";
export const COMMUNITY_IMAGE_UPLOAD_SUCCESS = "COMMUNITY_IMAGE_UPLOAD_SUCCESS";
export const COMMUNITY_IMAGE_UPLOAD_FAIL =  "COMMUNITY_IMAGE_UPLOAD_FAIL";

export const SEEN__POST = "SEEN__POST";


export const POST_COMMUNITY_COMMENT_REQUEST = "POST_COMMUNITY_COMMENT_REQUEST";
export const POST_COMMUNITY_COMMENT_SUCCESS = "POST_COMMUNITY_COMMENT_SUCCESS";
export const POST_COMMUNITY_COMMENT_FAIL = "POST_COMMUNITY_COMMENT_FAIL";

export const GET_COMMUNITY_POST_COMMENTS_REQUEST = "GET_COMMUNITY_POST_COMMENTS_REQUEST";
export const GET_COMMUNITY_POST_COMMENTS_SUCCESS = "GET_COMMUNITY_POST_COMMENTS_SUCCESS";
export const GET_COMMUNITY_POST_COMMENTS_FAIL = "GET_COMMUNITY_POST_COMMENTS_FAIL";
export const NEW_POST = "NEW_POST";

export const LIKE_COMMUNITY_COMMENT_REQUEST = "LIKE_COMMUNITY_COMMENT_REQUEST";
export const LIKE_COMMUNITY_COMMENT_SUCCESS = "LIKE_COMMUNITY_COMMENT_SUCCESS";
export const LIKE_COMMUNITY_COMMENT_FAIL = "LIKE_COMMUNITY_COMMENT_FAIL";

export const SHARE_COMMUNITY_COMMENT_REQUEST = "SHARE_COMMUNITY_COMMENT_REQUEST";
export const SHARE_COMMUNITY_COMMENT_SUCCESS = "SHARE_COMMUNITY_COMMENT_SUCCESS";
export const SHARE_COMMUNITY_COMMENT_FAIL = "SHARE_COMMUNITY_COMMENT_FAIL";
