
export const MESSAGE__SUCCESS = "MESSAGE__SUCCESS"
export const MESSAGE__ERROR = "MESSAGE__ERROR"
export const MESSAGE__WARNING = "MESSAGE__WARNING"
export const CLEAR__MESSAGE = "CLEAR__MESSAGE"

export const CLOSE__MODAL = "CLOSE__MODAL"
export const OPEN__MODAL = "OPEN__MODAL"


export const CHANGE__HOME__PAGINATION__VALUE = "CHANGE__HOME__PAGINATION__VALUE"

export const CHANGE__COMMUNITY__PAGINATION__VALUE = "CHANGE__COMMUNITY__PAGINATION__VALUE"