
export const MESSAGE__SUCCESS = "MESSAGE__SUCCESS"
export const MESSAGE__ERROR = "MESSAGE__ERROR"
export const MESSAGE__WARNING = "MESSAGE__WARNING"
export const CLEAR__MESSAGE = "CLEAR__MESSAGE"

export const CLOSE__MODAL = "CLOSE__MODAL"
export const OPEN__MODAL = "OPEN__MODAL"